version: '3'

services:
  configuration-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6103:80"

  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"

  profiles-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6108:80"