version: '3'

services:
  notification-api:
    image: smarthotels/notification
    build:
      context: .
      dockerfile: SmartHotel.Services.Notification/Dockerfile

  configuration-api:
    image: smarthotels/configuration
    build:
      context: ./SmartHotel.Services.Configuration
      dockerfile: Dockerfile

  profiles-api:
    image: smarthotels/profiles
    build:
      context: ./SmartHotel.Services.Profile
      dockerfile: Dockerfile

  sql-data:
    image: microsoft/mssql-server-linux:2017-GA