version: '3'

services:
  booking-api:
    image: smarthotels/booking
    build: 
      context: .
      dockerfile: SmartHotel.Services.Booking/Dockerfile

  hotel-api:
    image: smarthotels/hotel
    build:
      context: .
      dockerfile: SmartHotel.Services.Hotel/Dockerfile

  notification-api:
    image: smarthotels/notification
    build:
      context: .
      dockerfile: SmartHotel.Services.Notification/Dockerfile

  configuration-api:
    image: smarthotels/configuration
    build:
      context: ./SmartHotel.Services.Configuration
      dockerfile: Dockerfile

  profiles-api:
    image: smarthotels/profiles
    build:
      context: ./SmartHotel.Services.Profile
      dockerfile: Dockerfile

  discount-api:
    image: smarthotels/discount
    build:
      context: ./SmartHotel.Services.Discount
      dockerfile: Dockerfile

  sql-data:
    image: microsoft/mssql-server-linux:2017-GA