version: '3'

services:
  booking-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-data;Database=SmartHotel.Booking;User Id=sa;Password=Passw0rd!
    ports:
      - "6100:80"

  hotel-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-data;Database=SmartHotel.Hotel;User Id=sa;Password=Passw0rd!
      - discountsrv=http://discount-api/
    ports:
      - "6101:80"

  configuration-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6103:80"

  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"

  profiles-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-data;Database=SmartHotel.Profile;User Id=sa;Password=Passw0rd!
    ports:
      - "6108:80"

  discount-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - profilesvc=http://profiles-api/
    ports:
      - "6107:80"

  review-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-data;Database=SmartHotel.Review;User Id=sa;Password=Passw0rd!
    ports:
      - "6106:80"

  task-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-data;Database=SmartHotel.Task;User Id=sa;Password=Passw0rd!
    ports:
      - "6104:80"

  suggestion-api:
    environment:
      - PORT=80
      - SUGGESTONS_DATABASE_URL=mssql://sa:Passw0rd!@sql-data:1433/SuggestionsDb
      - NODE_ENV=docker
    ports:
      - "6102:80"

  sql-data:
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "6433:1433"