version: '3'

services:
  configuration-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6103:80"

  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"

  profiles-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-data;Database=SmartHotel.Services.Profile;User Id=sa;Password=Passw0rd!
    ports:
      - "6108:80"

  discount-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - profilesvc=http://profiles-api/
    ports:
      - "6107:80"

  sql-data:
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "6433:1433"